<html>
    <head></head>
    <body>
        <h3><?=$this->title;?></h3>
        
        <form action="/login/register" method="post">
            Login: <input type="text" value="" name="name"><br>
            Email: <input type="text" value="" name="email"><br>
            Password: <input type="text" value="" name="password"><br>
            Confirm password: <input type="text" value="" name="password_2"><br>
            <input type="submit" value="Зарегистрироваться">
        </form>
    </body>
</html>